apiVersion: v1
kind: ConfigMap
metadata:
  name: contacts-queue-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RABBITMQ_CONNECTION_STRING: "amqps://admin:admin@rabbitmq:5672/"
  RabbitMq:Host: "amqps://admin:admin@rabbitmq:5672/"
