# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: contacts-queue-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RABBITMQ_CONNECTION_STRING: "amqps://admin:admin@rabbitmq:5672/"

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-queue-deployment
  labels:
    app: contacts-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-queue
  template:
    metadata:
      labels:
        app: contacts-queue
    spec:
      containers:
        - name: contacts-queue
          image: gugol94/fiapcontacts-queue:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: contacts-queue-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
---

# Service
apiVersion: v1
kind: Service
metadata:
  name: contacts-queue-service
  labels:
    app: contacts-queue
spec:
  type: NodePort
  selector:
    app: contacts-queue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081