apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-queue-deployment
  labels:
    app: contacts-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-queue
  template:
    metadata:
      labels:
        app: contacts-queue
    spec:
      containers:
        - name: contacts-queue
          image: gugol94/fiapcontacts-queue:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: contacts-queue-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "150m"
