apiVersion: v1
kind: Service
metadata:
  name: contacts-queue-service
  labels:
    app: contacts-queue
spec:
  type: NodePort
  selector:
    app: contacts-queue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
